#############################################################################
# Makefile for building: RTPServer
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  RTPServer.pro
# Template: app
# Command: /media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/bin/qmake -o Makefile RTPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DDEBUG -DQT_QML_DEBUG
CFLAGS        = -pipe -g -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Isdk/include -I/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/linux-g++
QMAKE         = /media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = RTPServer1.0.0
DISTDIR = /home/zm/Desktop/RTPServer/.tmp/RTPServer1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/home/zm/Desktop/RTPServer/sdk/lib/ -ljrtp -ljthread -pthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/rtp/rtpsession.cpp \
		src/core/logger.cpp \
		src/serverengine.cpp \
		src/core/abstractthread.cpp \
		src/rtp/rtpusermanager.cpp \
		src/rtp/queue.cpp 
OBJECTS       = main.o \
		rtpsession.o \
		logger.o \
		serverengine.o \
		abstractthread.o \
		rtpusermanager.o \
		queue.o
DIST          = /media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/spec_pre.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/unix.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/linux.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/sanitize.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/gcc-base.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/g++-base.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/g++-unix.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/qconfig.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qt_functions.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qt_config.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/toolchain.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/default_pre.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/resolve_config.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/default_post.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qml_debug.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/warn_on.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qmake_use.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/file_copies.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/exceptions.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/yacc.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/lex.prf \
		RTPServer.pro src/rtp/rtpsession.h \
		src/core/config.h \
		src/core/logger.h \
		src/core/error.h \
		src/serverengine.h \
		src/rtp/rtpusermanager.h \
		src/core/abstractqueue.h \
		src/core/abstractthread.h \
		src/rtp/queue.h src/main.cpp \
		src/rtp/rtpsession.cpp \
		src/core/logger.cpp \
		src/serverengine.cpp \
		src/core/abstractthread.cpp \
		src/rtp/rtpusermanager.cpp \
		src/rtp/queue.cpp
QMAKE_TARGET  = RTPServer
DESTDIR       = 
TARGET        = RTPServer


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RTPServer.pro /media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf /media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/spec_pre.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/unix.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/linux.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/sanitize.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/gcc-base.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/g++-base.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/g++-unix.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/qconfig.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qt_functions.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qt_config.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/toolchain.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/default_pre.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/resolve_config.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/default_post.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qml_debug.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/warn_on.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qmake_use.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/file_copies.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/exceptions.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/yacc.prf \
		/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/lex.prf \
		RTPServer.pro
	$(QMAKE) -o Makefile RTPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/spec_pre.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/unix.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/linux.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/sanitize.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/gcc-base.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/g++-base.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/common/g++-unix.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/qconfig.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_location.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_script.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qt_functions.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qt_config.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/linux-g++/qmake.conf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/exclusive_builds.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/toolchain.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/default_pre.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/resolve_config.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/default_post.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qml_debug.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/warn_on.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/qmake_use.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/file_copies.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/testcase_targets.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/exceptions.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/yacc.prf:
/media/zm/_dde_data/Qt-5.11.2/5.11.2/gcc_64/mkspecs/features/lex.prf:
RTPServer.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile RTPServer.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp src/serverengine.h \
		src/core/config.h \
		src/rtp/rtpsession.h \
		sdk/include/jrtplib3/rtpsession.h \
		sdk/include/jrtplib3/rtpconfig.h \
		sdk/include/jrtplib3/rtplibraryversion.h \
		sdk/include/jrtplib3/rtppacketbuilder.h \
		sdk/include/jrtplib3/rtperrors.h \
		sdk/include/jrtplib3/rtpdefines.h \
		sdk/include/jrtplib3/rtprandom.h \
		sdk/include/jrtplib3/rtptypes.h \
		sdk/include/jrtplib3/rtptimeutilities.h \
		sdk/include/jrtplib3/rtpmemoryobject.h \
		sdk/include/jrtplib3/rtpmemorymanager.h \
		sdk/include/jrtplib3/rtpsessionsources.h \
		sdk/include/jrtplib3/rtpsources.h \
		sdk/include/jrtplib3/rtpkeyhashtable.h \
		sdk/include/jrtplib3/rtcpsdespacket.h \
		sdk/include/jrtplib3/rtcppacket.h \
		sdk/include/jrtplib3/rtpstructs.h \
		sdk/include/jrtplib3/rtptransmitter.h \
		sdk/include/jrtplib3/rtpcollisionlist.h \
		sdk/include/jrtplib3/rtpaddress.h \
		sdk/include/jrtplib3/rtcpscheduler.h \
		sdk/include/jrtplib3/rtcppacketbuilder.h \
		sdk/include/jrtplib3/rtcpsdesinfo.h \
		sdk/include/jrtplib3/rtcpcompoundpacketbuilder.h \
		sdk/include/jrtplib3/rtcpcompoundpacket.h \
		sdk/include/jthread/jmutex.h \
		sdk/include/jthread/jthreadconfig.h \
		sdk/include/jrtplib3/rtppacket.h \
		sdk/include/jrtplib3/rtpipv4address.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

rtpsession.o: src/rtp/rtpsession.cpp src/rtp/rtpsession.h \
		src/core/config.h \
		sdk/include/jrtplib3/rtpsession.h \
		sdk/include/jrtplib3/rtpconfig.h \
		sdk/include/jrtplib3/rtplibraryversion.h \
		sdk/include/jrtplib3/rtppacketbuilder.h \
		sdk/include/jrtplib3/rtperrors.h \
		sdk/include/jrtplib3/rtpdefines.h \
		sdk/include/jrtplib3/rtprandom.h \
		sdk/include/jrtplib3/rtptypes.h \
		sdk/include/jrtplib3/rtptimeutilities.h \
		sdk/include/jrtplib3/rtpmemoryobject.h \
		sdk/include/jrtplib3/rtpmemorymanager.h \
		sdk/include/jrtplib3/rtpsessionsources.h \
		sdk/include/jrtplib3/rtpsources.h \
		sdk/include/jrtplib3/rtpkeyhashtable.h \
		sdk/include/jrtplib3/rtcpsdespacket.h \
		sdk/include/jrtplib3/rtcppacket.h \
		sdk/include/jrtplib3/rtpstructs.h \
		sdk/include/jrtplib3/rtptransmitter.h \
		sdk/include/jrtplib3/rtpcollisionlist.h \
		sdk/include/jrtplib3/rtpaddress.h \
		sdk/include/jrtplib3/rtcpscheduler.h \
		sdk/include/jrtplib3/rtcppacketbuilder.h \
		sdk/include/jrtplib3/rtcpsdesinfo.h \
		sdk/include/jrtplib3/rtcpcompoundpacketbuilder.h \
		sdk/include/jrtplib3/rtcpcompoundpacket.h \
		sdk/include/jthread/jmutex.h \
		sdk/include/jthread/jthreadconfig.h \
		sdk/include/jrtplib3/rtppacket.h \
		sdk/include/jrtplib3/rtpsourcedata.h \
		sdk/include/jrtplib3/rtcpapppacket.h \
		sdk/include/jrtplib3/rtcpsrpacket.h \
		sdk/include/jrtplib3/rtcprrpacket.h \
		sdk/include/jrtplib3/rtcpbyepacket.h \
		sdk/include/jrtplib3/rtpipv4address.h \
		src/core/logger.h \
		src/core/error.h \
		sdk/include/spdlog/spdlog.h \
		sdk/include/spdlog/common.h \
		sdk/include/spdlog/tweakme.h \
		sdk/include/spdlog/details/null_mutex.h \
		sdk/include/spdlog/fmt/fmt.h \
		sdk/include/spdlog/fmt/bundled/core.h \
		sdk/include/spdlog/fmt/bundled/format.h \
		sdk/include/spdlog/fmt/bundled/format-inl.h \
		sdk/include/spdlog/details/registry.h \
		sdk/include/spdlog/details/periodic_worker.h \
		sdk/include/spdlog/logger.h \
		sdk/include/spdlog/formatter.h \
		sdk/include/spdlog/details/log_msg.h \
		sdk/include/spdlog/details/os.h \
		sdk/include/spdlog/sinks/sink.h \
		sdk/include/spdlog/details/pattern_formatter.h \
		sdk/include/spdlog/details/fmt_helper.h \
		sdk/include/spdlog/details/logger_impl.h \
		sdk/include/spdlog/sinks/wincolor_sink.h \
		sdk/include/spdlog/details/console_globals.h \
		sdk/include/spdlog/sinks/ansicolor_sink.h \
		sdk/include/spdlog/version.h \
		sdk/include/spdlog/async.h \
		sdk/include/spdlog/async_logger.h \
		sdk/include/spdlog/details/async_logger_impl.h \
		sdk/include/spdlog/details/thread_pool.h \
		sdk/include/spdlog/details/mpmc_blocking_q.h \
		sdk/include/spdlog/details/circular_q.h \
		sdk/include/spdlog/sinks/stdout_sinks.h \
		sdk/include/spdlog/sinks/rotating_file_sink.h \
		sdk/include/spdlog/details/file_helper.h \
		sdk/include/spdlog/sinks/base_sink.h \
		src/rtp/rtpusermanager.h \
		sdk/include/jrtplib3/rtpsessionparams.h \
		sdk/include/jrtplib3/rtpudpv4transmitter.h \
		sdk/include/jrtplib3/rtpipv4destination.h \
		sdk/include/jrtplib3/rtphashtable.h \
		sdk/include/jrtplib3/rtpsocketutil.h \
		sdk/include/jrtplib3/rtpabortdescriptors.h \
		src/serverengine.h \
		src/rtp/queue.h \
		src/core/abstractqueue.h \
		src/core/abstractthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rtpsession.o src/rtp/rtpsession.cpp

logger.o: src/core/logger.cpp src/core/logger.h \
		src/core/config.h \
		src/core/error.h \
		sdk/include/spdlog/spdlog.h \
		sdk/include/spdlog/common.h \
		sdk/include/spdlog/tweakme.h \
		sdk/include/spdlog/details/null_mutex.h \
		sdk/include/spdlog/fmt/fmt.h \
		sdk/include/spdlog/fmt/bundled/core.h \
		sdk/include/spdlog/fmt/bundled/format.h \
		sdk/include/spdlog/fmt/bundled/format-inl.h \
		sdk/include/spdlog/details/registry.h \
		sdk/include/spdlog/details/periodic_worker.h \
		sdk/include/spdlog/logger.h \
		sdk/include/spdlog/formatter.h \
		sdk/include/spdlog/details/log_msg.h \
		sdk/include/spdlog/details/os.h \
		sdk/include/spdlog/sinks/sink.h \
		sdk/include/spdlog/details/pattern_formatter.h \
		sdk/include/spdlog/details/fmt_helper.h \
		sdk/include/spdlog/details/logger_impl.h \
		sdk/include/spdlog/sinks/wincolor_sink.h \
		sdk/include/spdlog/details/console_globals.h \
		sdk/include/spdlog/sinks/ansicolor_sink.h \
		sdk/include/spdlog/version.h \
		sdk/include/spdlog/async.h \
		sdk/include/spdlog/async_logger.h \
		sdk/include/spdlog/details/async_logger_impl.h \
		sdk/include/spdlog/details/thread_pool.h \
		sdk/include/spdlog/details/mpmc_blocking_q.h \
		sdk/include/spdlog/details/circular_q.h \
		sdk/include/spdlog/sinks/stdout_sinks.h \
		sdk/include/spdlog/sinks/rotating_file_sink.h \
		sdk/include/spdlog/details/file_helper.h \
		sdk/include/spdlog/sinks/base_sink.h \
		sdk/include/jrtplib3/rtperrors.h \
		sdk/include/jrtplib3/rtpconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o src/core/logger.cpp

serverengine.o: src/serverengine.cpp src/serverengine.h \
		src/core/config.h \
		src/rtp/rtpsession.h \
		sdk/include/jrtplib3/rtpsession.h \
		sdk/include/jrtplib3/rtpconfig.h \
		sdk/include/jrtplib3/rtplibraryversion.h \
		sdk/include/jrtplib3/rtppacketbuilder.h \
		sdk/include/jrtplib3/rtperrors.h \
		sdk/include/jrtplib3/rtpdefines.h \
		sdk/include/jrtplib3/rtprandom.h \
		sdk/include/jrtplib3/rtptypes.h \
		sdk/include/jrtplib3/rtptimeutilities.h \
		sdk/include/jrtplib3/rtpmemoryobject.h \
		sdk/include/jrtplib3/rtpmemorymanager.h \
		sdk/include/jrtplib3/rtpsessionsources.h \
		sdk/include/jrtplib3/rtpsources.h \
		sdk/include/jrtplib3/rtpkeyhashtable.h \
		sdk/include/jrtplib3/rtcpsdespacket.h \
		sdk/include/jrtplib3/rtcppacket.h \
		sdk/include/jrtplib3/rtpstructs.h \
		sdk/include/jrtplib3/rtptransmitter.h \
		sdk/include/jrtplib3/rtpcollisionlist.h \
		sdk/include/jrtplib3/rtpaddress.h \
		sdk/include/jrtplib3/rtcpscheduler.h \
		sdk/include/jrtplib3/rtcppacketbuilder.h \
		sdk/include/jrtplib3/rtcpsdesinfo.h \
		sdk/include/jrtplib3/rtcpcompoundpacketbuilder.h \
		sdk/include/jrtplib3/rtcpcompoundpacket.h \
		sdk/include/jthread/jmutex.h \
		sdk/include/jthread/jthreadconfig.h \
		sdk/include/jrtplib3/rtppacket.h \
		sdk/include/jrtplib3/rtpipv4address.h \
		sdk/include/jrtplib3/rtpudpv4transmitter.h \
		sdk/include/jrtplib3/rtpipv4destination.h \
		sdk/include/jrtplib3/rtphashtable.h \
		sdk/include/jrtplib3/rtpsocketutil.h \
		sdk/include/jrtplib3/rtpabortdescriptors.h \
		sdk/include/jrtplib3/rtpsessionparams.h \
		src/core/logger.h \
		src/core/error.h \
		sdk/include/spdlog/spdlog.h \
		sdk/include/spdlog/common.h \
		sdk/include/spdlog/tweakme.h \
		sdk/include/spdlog/details/null_mutex.h \
		sdk/include/spdlog/fmt/fmt.h \
		sdk/include/spdlog/fmt/bundled/core.h \
		sdk/include/spdlog/fmt/bundled/format.h \
		sdk/include/spdlog/fmt/bundled/format-inl.h \
		sdk/include/spdlog/details/registry.h \
		sdk/include/spdlog/details/periodic_worker.h \
		sdk/include/spdlog/logger.h \
		sdk/include/spdlog/formatter.h \
		sdk/include/spdlog/details/log_msg.h \
		sdk/include/spdlog/details/os.h \
		sdk/include/spdlog/sinks/sink.h \
		sdk/include/spdlog/details/pattern_formatter.h \
		sdk/include/spdlog/details/fmt_helper.h \
		sdk/include/spdlog/details/logger_impl.h \
		sdk/include/spdlog/sinks/wincolor_sink.h \
		sdk/include/spdlog/details/console_globals.h \
		sdk/include/spdlog/sinks/ansicolor_sink.h \
		sdk/include/spdlog/version.h \
		sdk/include/spdlog/async.h \
		sdk/include/spdlog/async_logger.h \
		sdk/include/spdlog/details/async_logger_impl.h \
		sdk/include/spdlog/details/thread_pool.h \
		sdk/include/spdlog/details/mpmc_blocking_q.h \
		sdk/include/spdlog/details/circular_q.h \
		sdk/include/spdlog/sinks/stdout_sinks.h \
		sdk/include/spdlog/sinks/rotating_file_sink.h \
		sdk/include/spdlog/details/file_helper.h \
		sdk/include/spdlog/sinks/base_sink.h \
		src/rtp/rtpusermanager.h \
		sdk/include/jrtplib3/rtpsourcedata.h \
		src/rtp/queue.h \
		src/core/abstractqueue.h \
		src/core/abstractthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serverengine.o src/serverengine.cpp

abstractthread.o: src/core/abstractthread.cpp src/core/abstractthread.h \
		src/core/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractthread.o src/core/abstractthread.cpp

rtpusermanager.o: src/rtp/rtpusermanager.cpp src/rtp/rtpusermanager.h \
		src/rtp/rtpsession.h \
		src/core/config.h \
		sdk/include/jrtplib3/rtpsession.h \
		sdk/include/jrtplib3/rtpconfig.h \
		sdk/include/jrtplib3/rtplibraryversion.h \
		sdk/include/jrtplib3/rtppacketbuilder.h \
		sdk/include/jrtplib3/rtperrors.h \
		sdk/include/jrtplib3/rtpdefines.h \
		sdk/include/jrtplib3/rtprandom.h \
		sdk/include/jrtplib3/rtptypes.h \
		sdk/include/jrtplib3/rtptimeutilities.h \
		sdk/include/jrtplib3/rtpmemoryobject.h \
		sdk/include/jrtplib3/rtpmemorymanager.h \
		sdk/include/jrtplib3/rtpsessionsources.h \
		sdk/include/jrtplib3/rtpsources.h \
		sdk/include/jrtplib3/rtpkeyhashtable.h \
		sdk/include/jrtplib3/rtcpsdespacket.h \
		sdk/include/jrtplib3/rtcppacket.h \
		sdk/include/jrtplib3/rtpstructs.h \
		sdk/include/jrtplib3/rtptransmitter.h \
		sdk/include/jrtplib3/rtpcollisionlist.h \
		sdk/include/jrtplib3/rtpaddress.h \
		sdk/include/jrtplib3/rtcpscheduler.h \
		sdk/include/jrtplib3/rtcppacketbuilder.h \
		sdk/include/jrtplib3/rtcpsdesinfo.h \
		sdk/include/jrtplib3/rtcpcompoundpacketbuilder.h \
		sdk/include/jrtplib3/rtcpcompoundpacket.h \
		sdk/include/jthread/jmutex.h \
		sdk/include/jthread/jthreadconfig.h \
		sdk/include/jrtplib3/rtppacket.h \
		sdk/include/jrtplib3/rtpsourcedata.h \
		sdk/include/jrtplib3/rtpipv4address.h \
		sdk/include/jrtplib3/rtpsessionparams.h \
		sdk/include/jrtplib3/rtpudpv4transmitter.h \
		sdk/include/jrtplib3/rtpipv4destination.h \
		sdk/include/jrtplib3/rtphashtable.h \
		sdk/include/jrtplib3/rtpsocketutil.h \
		sdk/include/jrtplib3/rtpabortdescriptors.h \
		src/core/logger.h \
		src/core/error.h \
		sdk/include/spdlog/spdlog.h \
		sdk/include/spdlog/common.h \
		sdk/include/spdlog/tweakme.h \
		sdk/include/spdlog/details/null_mutex.h \
		sdk/include/spdlog/fmt/fmt.h \
		sdk/include/spdlog/fmt/bundled/core.h \
		sdk/include/spdlog/fmt/bundled/format.h \
		sdk/include/spdlog/fmt/bundled/format-inl.h \
		sdk/include/spdlog/details/registry.h \
		sdk/include/spdlog/details/periodic_worker.h \
		sdk/include/spdlog/logger.h \
		sdk/include/spdlog/formatter.h \
		sdk/include/spdlog/details/log_msg.h \
		sdk/include/spdlog/details/os.h \
		sdk/include/spdlog/sinks/sink.h \
		sdk/include/spdlog/details/pattern_formatter.h \
		sdk/include/spdlog/details/fmt_helper.h \
		sdk/include/spdlog/details/logger_impl.h \
		sdk/include/spdlog/sinks/wincolor_sink.h \
		sdk/include/spdlog/details/console_globals.h \
		sdk/include/spdlog/sinks/ansicolor_sink.h \
		sdk/include/spdlog/version.h \
		sdk/include/spdlog/async.h \
		sdk/include/spdlog/async_logger.h \
		sdk/include/spdlog/details/async_logger_impl.h \
		sdk/include/spdlog/details/thread_pool.h \
		sdk/include/spdlog/details/mpmc_blocking_q.h \
		sdk/include/spdlog/details/circular_q.h \
		sdk/include/spdlog/sinks/stdout_sinks.h \
		sdk/include/spdlog/sinks/rotating_file_sink.h \
		sdk/include/spdlog/details/file_helper.h \
		sdk/include/spdlog/sinks/base_sink.h \
		src/serverengine.h \
		src/rtp/queue.h \
		src/core/abstractqueue.h \
		src/core/abstractthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rtpusermanager.o src/rtp/rtpusermanager.cpp

queue.o: src/rtp/queue.cpp src/rtp/queue.h \
		src/core/abstractqueue.h \
		src/core/abstractthread.h \
		src/core/config.h \
		src/rtp/rtpsession.h \
		sdk/include/jrtplib3/rtpsession.h \
		sdk/include/jrtplib3/rtpconfig.h \
		sdk/include/jrtplib3/rtplibraryversion.h \
		sdk/include/jrtplib3/rtppacketbuilder.h \
		sdk/include/jrtplib3/rtperrors.h \
		sdk/include/jrtplib3/rtpdefines.h \
		sdk/include/jrtplib3/rtprandom.h \
		sdk/include/jrtplib3/rtptypes.h \
		sdk/include/jrtplib3/rtptimeutilities.h \
		sdk/include/jrtplib3/rtpmemoryobject.h \
		sdk/include/jrtplib3/rtpmemorymanager.h \
		sdk/include/jrtplib3/rtpsessionsources.h \
		sdk/include/jrtplib3/rtpsources.h \
		sdk/include/jrtplib3/rtpkeyhashtable.h \
		sdk/include/jrtplib3/rtcpsdespacket.h \
		sdk/include/jrtplib3/rtcppacket.h \
		sdk/include/jrtplib3/rtpstructs.h \
		sdk/include/jrtplib3/rtptransmitter.h \
		sdk/include/jrtplib3/rtpcollisionlist.h \
		sdk/include/jrtplib3/rtpaddress.h \
		sdk/include/jrtplib3/rtcpscheduler.h \
		sdk/include/jrtplib3/rtcppacketbuilder.h \
		sdk/include/jrtplib3/rtcpsdesinfo.h \
		sdk/include/jrtplib3/rtcpcompoundpacketbuilder.h \
		sdk/include/jrtplib3/rtcpcompoundpacket.h \
		sdk/include/jthread/jmutex.h \
		sdk/include/jthread/jthreadconfig.h \
		sdk/include/jrtplib3/rtppacket.h \
		src/rtp/rtpusermanager.h \
		sdk/include/jrtplib3/rtpsourcedata.h \
		sdk/include/jrtplib3/rtpipv4address.h \
		sdk/include/jrtplib3/rtpsessionparams.h \
		sdk/include/jrtplib3/rtpudpv4transmitter.h \
		sdk/include/jrtplib3/rtpipv4destination.h \
		sdk/include/jrtplib3/rtphashtable.h \
		sdk/include/jrtplib3/rtpsocketutil.h \
		sdk/include/jrtplib3/rtpabortdescriptors.h \
		src/core/logger.h \
		src/core/error.h \
		sdk/include/spdlog/spdlog.h \
		sdk/include/spdlog/common.h \
		sdk/include/spdlog/tweakme.h \
		sdk/include/spdlog/details/null_mutex.h \
		sdk/include/spdlog/fmt/fmt.h \
		sdk/include/spdlog/fmt/bundled/core.h \
		sdk/include/spdlog/fmt/bundled/format.h \
		sdk/include/spdlog/fmt/bundled/format-inl.h \
		sdk/include/spdlog/details/registry.h \
		sdk/include/spdlog/details/periodic_worker.h \
		sdk/include/spdlog/logger.h \
		sdk/include/spdlog/formatter.h \
		sdk/include/spdlog/details/log_msg.h \
		sdk/include/spdlog/details/os.h \
		sdk/include/spdlog/sinks/sink.h \
		sdk/include/spdlog/details/pattern_formatter.h \
		sdk/include/spdlog/details/fmt_helper.h \
		sdk/include/spdlog/details/logger_impl.h \
		sdk/include/spdlog/sinks/wincolor_sink.h \
		sdk/include/spdlog/details/console_globals.h \
		sdk/include/spdlog/sinks/ansicolor_sink.h \
		sdk/include/spdlog/version.h \
		sdk/include/spdlog/async.h \
		sdk/include/spdlog/async_logger.h \
		sdk/include/spdlog/details/async_logger_impl.h \
		sdk/include/spdlog/details/thread_pool.h \
		sdk/include/spdlog/details/mpmc_blocking_q.h \
		sdk/include/spdlog/details/circular_q.h \
		sdk/include/spdlog/sinks/stdout_sinks.h \
		sdk/include/spdlog/sinks/rotating_file_sink.h \
		sdk/include/spdlog/details/file_helper.h \
		sdk/include/spdlog/sinks/base_sink.h \
		src/serverengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queue.o src/rtp/queue.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

